### ISSUE TITLE
problem about models

### ISSUE THREAD

**Issue by gyxx323** [edwardnguyen1705/robotic-grasping-cornell#11]
When I run the demo: `python3 demo.py`

I encountered the following error：
```
GPUs memory available: {0: 3347}
GPUs memory available > 1024 MB: ['0']
Traceback (most recent call last):
  File "demo.py", line 83, in <module>
    model = load_model(gpus)
  File "demo.py", line 41, in load_model
    model.load_state_dict(checkpoint['model'])
KeyError: 'model'
```

May I ask what causes this? And how should I solve it？ 

Thank you!

**Comment by edwardnguyen1705** [comment]
> 

Hi @gyxx323 ,
please try `print((dir(checkpoint))` for your info. You may try:

```
model.load_state_dict(checkpoint['model_state_dict'])
or
model.load_state_dict(checkpoint['model_state'])
```
