### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'models'

### ISSUE THREAD

**Issue by Ultraopxt** [edwardnguyen1705/robotic-grasping-cornell#5]
Thanks for your job.Irun the train.py and got an error like:

**Traceback (most recent call last):
  File "train.py", line 97, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "train.py", line 79, in main
    save_name = os.path.join(args.models, 'model_{}.ckpt'.format(epoch))
AttributeError: 'Namespace' object has no attribute 'models'**

**Comment by edwardnguyen1705** [comment]
@qingweihk sorry for the confusion.
You can either change `args.models` in the line 77 in the `train.py` to the path you want to save model
` save_name = os.path.join(args.models, 'model_{}.ckpt'.format(epoch))`

or add `parser.add_argument('--models', type=str, help='save model path', default='./models')` in the function 
`def parse_arguments(argv)` line 87 in `train.py`

**Comment by Ultraopxt** [comment]
> @qingweihk sorry for the confusion.
> You can either change `args.models` in the line 77 in the `train.py` to the path you want to save model
> ` save_name = os.path.join(args.models, 'model_{}.ckpt'.format(epoch))`
> 
> or add `parser.add_argument('--models', type=str, help='save model path', default='./models')` in the function
> `def parse_arguments(argv)` line 87 in `train.py`

Thanks!

And when I run demo.py,there no picture show but only have the result as folowing. How can i show the picture? Thanks

writing gt rectdb to ./dataset/grasp/cache/test_gt_rectdb.pkl
rect_pred: [116.59576   87.176025 167.13191  108.533676]
<Figure size 640x480 with 1 Axes>
rect_pred: [ 62.33284 124.46828 101.41604 144.732  ]
<Figure size 640x480 with 1 Axes>
rect_pred: [ 93.70439 108.87364 134.0095  129.7158 ]
<Figure size 640x480 with 1 Axes>
rect_pred: [ 66.66079 124.17807 107.42759 145.91763]
<Figure size 640x480 with 1 Axes>
rect_pred: [112.374504 117.3329   163.32973  138.29427 ]
<Figure size 640x480 with 1 Axes>
rect_pred: [ 40.17956 121.9376   80.92822 142.9861 ]
<Figure size 640x480 with 1 Axes>
rect_pred: [104.547    100.223145 147.13206  120.1029  ]
<Figure size 640x480 with 1 Axes>

**Comment by edwardnguyen1705** [comment]
you can try to save the figure [https://stackoverflow.com/questions/9622163/save-plot-to-image-file-instead-of-displaying-it-using-matplotlib](url)

**Comment by Ultraopxt** [comment]
> you can try to save the figure [https://stackoverflow.com/questions/9622163/save-plot-to-image-file-instead-of-displaying-it-using-matplotlib](url)

Thanks.But this page is empty?: the page show :No results matched your search.

**Comment by edwardnguyen1705** [comment]
just copy the link
